### PR TITLE
Add option for sending page view

### PR DESCRIPTION
**Pull request by kencaron**
Would be nice for [angularytics](https://github.com/mgonto/angularytics) and other SPA type apps I'm sure.

### CODE REVIEW

**Comment by kencaron** [comment]
Probably would've helped if I tested that it worked! Currently just using a combination of `gulp-replace` and `gulp-inject` for my analytics needs. I'll have a new PR this weekend.

**Comment by flugger** [comment]
Any updates on this matter?

**Comment by zhhz** [comment]
Sorry, I overlooked this PR. Now it's merged and available by NPM. Thanks.

**Comment by flugger** [comment]
Thanks, appreciated :)

**Comment by zhhz** [comment]
Thank you Alexander for pointing out this. And thanks Ken for the PR.

**Pull request merged**
